# Generated by Django 4.1.2 on 2022-10-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Humano',
        ),
    ]
